MESSAGE_CARTE_PAS_DANS_MAIN = "Erreur : la carte demandée n'est pas dans la main du joueur"
PAS_ASSEZ_CARTES_JOUEES = "Vous n'avez pas joué assez de cartes"
CARTE_INVALIDE = "Vous avez joué une carte invalide DIRE POURQUOI"
ID_JOUEUR_INCORRECT = "Id de joueur incorrect DIRE POURQUOI"
NUMERO_PILE_INCORRECT = "Numéro de pile incorrect, doit être 0 ou 1"
CARTE_TROP_PETITE = "Carte jouée dans pile montante trop faible"
CARTE_TROP_GRANDE = "Carte jouée dans pile descendante trop forte"
